eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:6059/eureka # value will get overriden if passed from external config

spring:
  cloud:
    config:
      enabled: true
  config:
    #import: "optional:configserver:http://config-server:6055"
    import: "optional:configserver:http://localhost:6055"

management:
  endpoints:
    web:
      exposure:
        include: '*'
